  - kind: argoproj.io/v1alpha1/applications
    port:
      entity:
        mappings:
          - identifier: .metadata.name + "-" + .metadata.namespace
            blueprint: '"argocdApp"'
            properties:
              status: .status.health.status
              syncStatus: .status.sync.status
              gitRepo: .spec.source.repoURL
              gitPath: .spec.source.path
              gitRev: .status.sync.revision
            relations:
              services: .metadata.namespace as $namespace | .status.resources | map(select(.kind == "Service") | .name + "-" + $namespace)
              deployments: .metadata.namespace as $namespace | .status.resources | map(select(.kind == "Deployment") | .name + "-" + $namespace)
              project: .spec.project + "-" + .metadata.namespace

  - kind: argoproj.io/v1alpha1/appproject
    port:
      entity:
        mappings:
          - identifier: .metadata.name + "-" + .metadata.namespace
            blueprint: '"argocdProject"'
            properties:
              name: .metadata.name
              title: .metadata.name
